# Generated by Django 5.2.8 on 2025-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_consumer', '0002_alter_broker_api_config_alter_script_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
